# Generated by Django 2.1.4 on 2018-12-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elec_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model_number',
        ),
    ]
