# Generated by Django 2.1.4 on 2018-12-30 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elec_shop', '0003_auto_20181221_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(default=None, help_text='\n            Name for the image.\n            Naming Scheme:\n            - Thumbnails must be named as <product_name>.thumbnail.<extension>\n            - Other images to be named as <product_name>.<1, 2, 3, ..>.<extension>\n        ', max_length=70),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field=600, help_text='\n            Image for the product. Must be a 600x600 field for a standard image and 200x200 for thumbnail.\n            Allowed extensions: PNG, JPG, JPEG.\n        ', max_length=200, upload_to='shop_prod_images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], width_field=600),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(editable=False, help_text='Auto generated field. Do not edit.', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='image',
            table='elec_shop_image',
        ),
    ]
