# Generated by Django 2.1.4 on 2019-01-02 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elec_shop', '0004_auto_20181230_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail_flag',
            field=models.BooleanField(default=False, help_text='\n        Check this field if the image uploaded is a thumbnail.\n        '),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field=600, help_text='\n        Image for the product.<br>\n        * Sizes:<br>\n        &nbsp;&nbsp;- 600x600px for regular images.<br>\n        &nbsp;&nbsp;- 200x200 for thumbnail<br>\n        * Allowed extensions:<br>\n        &nbsp;&nbsp;- PNG<br>\n        &nbsp;&nbsp;- JPG<br>\n        &nbsp;&nbsp;- JPEG<br>\n        ', max_length=200, upload_to='shop_prod_images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], width_field=600),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=models.CharField(default=None, help_text='\n        Name for the image.<br>\n        * Naming Scheme:<br>\n        &nbsp;&nbsp;- Thumbnails must be named as manufacturer_name.product_name.thumbnail.extension<br>\n        &nbsp;&nbsp;- Other images to be named as manufacturer_name.product_name.(1, 2, 3, ..).extension<br>\n        ', max_length=70),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(help_text='Price in INR.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='Auto generated field. Do not edit.', max_length=255, primary_key=True, serialize=False),
        ),
    ]
