# Generated by Django 2.1.4 on 2019-01-02 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elec_shop', '0005_auto_20190102_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='\n        Image for the product.<br>\n        * Sizes:<br>\n        &nbsp;&nbsp;- 600x600px for regular images.<br>\n        &nbsp;&nbsp;- 200x200 for thumbnail<br>\n        * Allowed extensions:<br>\n        &nbsp;&nbsp;- PNG<br>\n        &nbsp;&nbsp;- JPG<br>\n        &nbsp;&nbsp;- JPEG<br>\n        ', max_length=200, upload_to='shop_prod_images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
