# Generated by Django 2.1.4 on 2019-01-05 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elec_shop', '0007_auto_20190105_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(help_text='\n        Thumbnail for the product.<br>\n        * Size: 200x200px<br>\n        * Allowed Extensions:<br>\n        &nbsp;&nbsp;- PNG<br>\n        &nbsp;&nbsp;- JPG<br>\n        &nbsp;&nbsp;- JPEG<br>\n        ', max_length=200, upload_to='shop_prod_images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
