# Generated by Django 2.1.4 on 2019-01-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elec_shop', '0008_auto_20190105_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_name',
        ),
    ]
